tab_spaces = 4
fn_brace_style = "PreferSameLine"
struct_trailing_comma = "Never"
struct_lit_trailing_comma = "Never"
struct_lit_multiline_style = "ForceMulti"
enum_trailing_comma = false
max_width=120
hard_tabs=true
normalise_comments=false
wrap_comments=false